name: MacOS latest

on: [push, pull_request]

jobs:
  on_build_actions:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install package
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pygame==2.1.3.dev8
          python3 -m pip install .
      - name: Run Tests    
        run: python3 -m unittest
