name: Ubuntu latest

on: [ push, pull_request ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  Python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10', 3.11]
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        run: |
          # Add the deadsnakes PPA to install python
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get update
          sudo apt-get install python${{ matrix.python-version }}-dev
          sudo apt-get install python${{ matrix.python-version }}-distutils
      - name: Install dependencies
        run: |
          sudo apt install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev pkg-config -y
          python${{ matrix.python-version }} -m pip install setuptools -U
          python${{ matrix.python-version }} -m pip install pygame-ce
          python${{ matrix.python-version }} -m pip install .
      - name: Run Tests
        run: python${{ matrix.python-version }} -m unittest