name: Ubuntu latest

on: [ push, pull_request ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  Python:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # if a particular matrix build fails, don't skip the rest
      matrix:
        python-version: [3.8, 3.9, '3.10', 3.11, 3.12]
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        run: |
          # Add the deadsnakes PPA to install python
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          sudo apt-get update
          sudo apt-get install python${{ matrix.python-version }}-dev -y
          sudo apt-get install python${{ matrix.python-version }}-distutils -y
          python${{ matrix.python-version }} -m pip install --upgrade setuptools
          python${{ matrix.python-version }} -m pip install --upgrade pip
          python${{ matrix.python-version }} -m pip install wheel
          python${{ matrix.python-version }} -m pip install pygame-ce
          python${{ matrix.python-version }} -m pip install .

      - name: Run Tests
        run: python${{ matrix.python-version }} -m unittest