name: Windows latest

on: [ push, pull_request ]



jobs:
  Python:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9, '3.10', 3.11 ]
    steps:
      - uses: github/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          choco install -y python3 --version ${{ matrix.python-version }}
          python -m pip install setuptools -U
          python -m pip install pygame-ce
          python -m pip install .
      - name: Run Tests
        run:
          python -m unittest